### ISSUE TITLE
Remove print statement from logistol.int

### ISSUE THREAD

**Issue by bd-cameron-willden** [dsy109/tolerance#1]
Line 26 of logistol.int currently contains:
```
print(c(m,s))
```
I'm guessing was meant to be a temporary line of code for debugging. Suggestion to remove this line.

**Comment by dsy109** [comment]
@bd-cameron-willden Thank you for noting this unnecessary line, and apologies for a very delayed response.  This has been removed in version 3.0.0, which has just appeared on CRAN.
